Repository Team-O2/Back-end, pull requests merged in 2021-07, with the labels that each got.

#4 feature: challenge api
  nodemon.json
  package.json
  src/Loader/db.ts
  src/controller/auth.ts
  src/controller/challenge.ts
  src/controller/concert.ts
  src/index.ts
  src/interfaces/IChallenge.ts
  src/interfaces/IComment.ts
  src/interfaces/IUser.ts
  src/library/jwt.ts
  src/library/response.ts
  src/library/returnCode.ts
  src/middleware/auth.ts
  src/middleware/challenge.ts
  src/models/Admin.ts
  src/models/Challenge.ts
  src/models/Comment.ts
  src/models/Concert.ts
  src/models/User.ts
  src/service/authService.ts
  src/service/challengeService.ts
  src/service/concertService.ts
  tsconfig.json
Labels: enhancement

#5 fix: like api / feat: scrap api / refactor: else if -> if
  src/controller/challenge.ts
  src/interfaces/ILikes.ts
  src/interfaces/IScraps.ts
  src/service/challengeService.ts
Labels: enhancement

#7 Feature/concert
  src/controller/concert.ts
  src/index.ts
  src/interfaces/IConcert.ts
  src/models/Concert.ts
  src/service/adminService.ts
  src/service/concertService.ts
Labels: enhancement

#8 fix: patchChallenge
  src/controller/challenge.ts
  src/service/challengeService.ts
Labels: enhancement

#12 fix: challenge comments에 댓글 id 추가
  src/service/challengeService.ts
Labels: bug

#16 feat: get -> offset 추가
  src/controller/challenge.ts
  src/service/challengeService.ts
Labels: enhancement

#17 feat: 비밀번호 찾기 구현
  package.json
  src/controller/auth.ts
  src/interfaces/IUser.ts
  src/library/emailSender.ts
  src/library/emailTemplete.ejs
  src/models/User.ts
  src/service/authService.ts
Labels: enhancement

#18 feat: auth -> middleware로 변경
  src/controller/challenge.ts
  src/middleware/auth.ts
  src/service/challengeService.ts
Labels: enhancement

#23 feat: 내가 쓴 댓글, 내가 쓴 글 아카이빙, 내가 쓴 댓글 삭제
  src/controller/admin.ts
  src/controller/auth.ts
  src/controller/challenge.ts
  src/controller/concert.ts
  src/controller/user.ts
  src/middleware/auth.ts
  src/service/challengeService.ts
  src/service/userService.ts
Labels: enhancement

#24 feat: challenge, concert 관련 배지 로직 구현
  src/controller/challenge.ts
  src/interfaces/IChallenge.ts
  src/interfaces/IComment.ts
  src/interfaces/IConcert.ts
  src/interfaces/ILikes.ts
  src/interfaces/IScraps.ts
  src/interfaces/IUser.ts
  src/models/Challenge.ts
  src/models/User.ts
  src/service/challengeService.ts
  src/service/concertService.ts
  src/service/userService.ts
Labels: enhancement

#25 feat: 공지사항
  src/controller/admin.ts
  src/controller/notice.ts
  src/index.ts
  src/interfaces/IAdmin.ts
  src/interfaces/IConcert.ts
  src/middleware/challenge.ts
  src/middleware/upload.ts
  src/models/Admin.ts
  src/models/Concert.ts
  src/modules/upload.ts
  src/service/adminService.ts
  src/service/noticeService.ts
  src/service/userService.ts
Labels: enhancement

#26 feat: scheduler 구현
  package.json
  src/index.ts
  src/interfaces/IUser.ts
  src/models/User.ts
  src/service/schedulerService.ts
Labels: enhancement

#28 fix: admin cardiNum -> generation
  src/interfaces/IAdmin.ts
  src/models/Admin.ts
  src/service/adminService.ts
  src/service/schedulerService.ts
  src/service/userService.ts
Labels: invalid

#30 feat: challenge, 내가 쓴 댓글 관련
  src/controller/challenge.ts
  src/controller/user.ts
  src/service/challengeService.ts
  src/service/userService.ts
Labels: documentation

#35 fix: img 필드 추가, limit 조건 추가
  package-lock.json
  src/controller/admin.ts
  src/controller/challenge.ts
  src/controller/concert.ts
  src/controller/notice.ts
  src/controller/user.ts
  src/interfaces/IUser.ts
  src/models/User.ts
  src/service/adminService.ts
  src/service/challengeService.ts
  src/service/concertService.ts
  src/service/noticeService.ts
  src/service/schedulerService.ts
  src/service/userService.ts
Labels: enhancement

#46 update README.md
  README.md
Labels: documentation
